
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/nix/store/r9941n32g4wyvggz2703dlplbdq8a6rd-cmake-4.1.2/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/home/inurentto/.config/Code/User/globalStorage/github.copilot-chat/debugCommand/"
      - "/home/inurentto/.config/Code/User/globalStorage/github.copilot-chat/copilotCli/"
      - "/nix/store/flq8wn4dikbhn2nmqac31zbpv0lkii2w-glib-2.88.1-bin/bin/"
      - "/nix/store/wp1cshqv98i8abs8rcx91s54igqgll0f-gawk-5.4.0/bin/"
      - "/nix/store/gn94gpcp5q08x4v6g8mvw8v4r65rcjzk-gnugrep-3.12/bin/"
      - "/nix/store/kgxafhycw2kybbqih759ykc2043qyi5j-gnused-4.9/bin/"
      - "/nix/store/9ypz3flqsrl5xl495mm8h645gadjsxi1-coreutils-9.11/bin/"
      - "/nix/store/91d9n98grpqj93576zl27bd5x0khcsvv-which-2.23/bin/"
      - "/nix/store/74gap24knhy6dl59xnd7cksag4hns2vc-getconf-glibc-2.42-61/bin/"
      - "/run/wrappers/bin/"
      - "/home/inurentto/.local/share/flatpak/exports/bin/"
      - "/var/lib/flatpak/exports/bin/"
      - "/home/inurentto/.nix-profile/bin/"
      - "/home/inurentto/.local/state/nix/profile/bin/"
      - "/etc/profiles/per-user/inurentto/bin/"
      - "/nix/var/nix/profiles/default/bin/"
      - "/run/current-system/sw/bin/"
      - "/nix/store/mbyy19mdwnfvfwmdi0gqgggx0njvpl1w-binutils-wrapper-2.46/bin/"
      - "/nix/store/9k1lifnzmiybhh43argn30fb3sandm7a-hyprland-qtutils-0.1.5/bin/"
      - "/nix/store/k0mncnynr1dljv26jabaagyd3fspkzc8-pciutils-3.15.0/bin/"
      - "/nix/store/9c0l37g60k8w570jakcdz518m22dn9k8-pkgconf-wrapper-2.5.1/bin/"
    searched_directories:
      - "/home/inurentto/.config/Code/User/globalStorage/github.copilot-chat/debugCommand/uname"
      - "/home/inurentto/.config/Code/User/globalStorage/github.copilot-chat/copilotCli/uname"
      - "/nix/store/flq8wn4dikbhn2nmqac31zbpv0lkii2w-glib-2.88.1-bin/bin/uname"
      - "/nix/store/wp1cshqv98i8abs8rcx91s54igqgll0f-gawk-5.4.0/bin/uname"
      - "/nix/store/gn94gpcp5q08x4v6g8mvw8v4r65rcjzk-gnugrep-3.12/bin/uname"
      - "/nix/store/kgxafhycw2kybbqih759ykc2043qyi5j-gnused-4.9/bin/uname"
    found: "/nix/store/9ypz3flqsrl5xl495mm8h645gadjsxi1-coreutils-9.11/bin/uname"
    search_context:
      ENV{PATH}:
        - "/home/inurentto/.config/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/home/inurentto/.config/Code/User/globalStorage/github.copilot-chat/copilotCli"
        - "/nix/store/flq8wn4dikbhn2nmqac31zbpv0lkii2w-glib-2.88.1-bin/bin"
        - "/nix/store/wp1cshqv98i8abs8rcx91s54igqgll0f-gawk-5.4.0/bin"
        - "/nix/store/gn94gpcp5q08x4v6g8mvw8v4r65rcjzk-gnugrep-3.12/bin"
        - "/nix/store/kgxafhycw2kybbqih759ykc2043qyi5j-gnused-4.9/bin"
        - "/nix/store/9ypz3flqsrl5xl495mm8h645gadjsxi1-coreutils-9.11/bin"
        - "/nix/store/91d9n98grpqj93576zl27bd5x0khcsvv-which-2.23/bin"
        - "/nix/store/74gap24knhy6dl59xnd7cksag4hns2vc-getconf-glibc-2.42-61/bin"
        - "/run/wrappers/bin"
        - "/home/inurentto/.local/share/flatpak/exports/bin"
        - "/var/lib/flatpak/exports/bin"
        - "/home/inurentto/.nix-profile/bin"
        - "/home/inurentto/.local/state/nix/profile/bin"
        - "/home/inurentto/.local/state/nix/profile/bin"
        - "/etc/profiles/per-user/inurentto/bin"
        - "/nix/var/nix/profiles/default/bin"
        - "/run/current-system/sw/bin"
        - "/nix/store/mbyy19mdwnfvfwmdi0gqgggx0njvpl1w-binutils-wrapper-2.46/bin"
        - "/nix/store/9k1lifnzmiybhh43argn30fb3sandm7a-hyprland-qtutils-0.1.5/bin"
        - "/nix/store/k0mncnynr1dljv26jabaagyd3fspkzc8-pciutils-3.15.0/bin"
        - "/nix/store/9c0l37g60k8w570jakcdz518m22dn9k8-pkgconf-wrapper-2.5.1/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/nix/store/r9941n32g4wyvggz2703dlplbdq8a6rd-cmake-4.1.2/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt"
    message: |
      The system is: Linux - 7.0.12 - x86_64
  -
    kind: "find-v1"
    backtrace:
      - "/nix/store/r9941n32g4wyvggz2703dlplbdq8a6rd-cmake-4.1.2/share/cmake-4.1/Modules/CMakeUnixFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "gmake"
      - "make"
      - "smake"
    candidate_directories:
      - "/home/inurentto/.config/Code/User/globalStorage/github.copilot-chat/debugCommand/"
      - "/home/inurentto/.config/Code/User/globalStorage/github.copilot-chat/copilotCli/"
      - "/nix/store/flq8wn4dikbhn2nmqac31zbpv0lkii2w-glib-2.88.1-bin/bin/"
      - "/nix/store/wp1cshqv98i8abs8rcx91s54igqgll0f-gawk-5.4.0/bin/"
      - "/nix/store/gn94gpcp5q08x4v6g8mvw8v4r65rcjzk-gnugrep-3.12/bin/"
      - "/nix/store/kgxafhycw2kybbqih759ykc2043qyi5j-gnused-4.9/bin/"
      - "/nix/store/9ypz3flqsrl5xl495mm8h645gadjsxi1-coreutils-9.11/bin/"
      - "/nix/store/91d9n98grpqj93576zl27bd5x0khcsvv-which-2.23/bin/"
      - "/nix/store/74gap24knhy6dl59xnd7cksag4hns2vc-getconf-glibc-2.42-61/bin/"
      - "/run/wrappers/bin/"
      - "/home/inurentto/.local/share/flatpak/exports/bin/"
      - "/var/lib/flatpak/exports/bin/"
      - "/home/inurentto/.nix-profile/bin/"
      - "/home/inurentto/.local/state/nix/profile/bin/"
      - "/etc/profiles/per-user/inurentto/bin/"
      - "/nix/var/nix/profiles/default/bin/"
      - "/run/current-system/sw/bin/"
      - "/nix/store/mbyy19mdwnfvfwmdi0gqgggx0njvpl1w-binutils-wrapper-2.46/bin/"
      - "/nix/store/9k1lifnzmiybhh43argn30fb3sandm7a-hyprland-qtutils-0.1.5/bin/"
      - "/nix/store/k0mncnynr1dljv26jabaagyd3fspkzc8-pciutils-3.15.0/bin/"
      - "/nix/store/9c0l37g60k8w570jakcdz518m22dn9k8-pkgconf-wrapper-2.5.1/bin/"
    searched_directories:
      - "/home/inurentto/.config/Code/User/globalStorage/github.copilot-chat/debugCommand/gmake"
      - "/home/inurentto/.config/Code/User/globalStorage/github.copilot-chat/copilotCli/gmake"
      - "/nix/store/flq8wn4dikbhn2nmqac31zbpv0lkii2w-glib-2.88.1-bin/bin/gmake"
      - "/nix/store/wp1cshqv98i8abs8rcx91s54igqgll0f-gawk-5.4.0/bin/gmake"
      - "/nix/store/gn94gpcp5q08x4v6g8mvw8v4r65rcjzk-gnugrep-3.12/bin/gmake"
      - "/nix/store/kgxafhycw2kybbqih759ykc2043qyi5j-gnused-4.9/bin/gmake"
      - "/nix/store/9ypz3flqsrl5xl495mm8h645gadjsxi1-coreutils-9.11/bin/gmake"
      - "/nix/store/91d9n98grpqj93576zl27bd5x0khcsvv-which-2.23/bin/gmake"
      - "/nix/store/74gap24knhy6dl59xnd7cksag4hns2vc-getconf-glibc-2.42-61/bin/gmake"
      - "/run/wrappers/bin/gmake"
      - "/home/inurentto/.local/share/flatpak/exports/bin/gmake"
      - "/var/lib/flatpak/exports/bin/gmake"
      - "/home/inurentto/.nix-profile/bin/gmake"
      - "/home/inurentto/.local/state/nix/profile/bin/gmake"
      - "/etc/profiles/per-user/inurentto/bin/gmake"
      - "/nix/var/nix/profiles/default/bin/gmake"
      - "/run/current-system/sw/bin/gmake"
      - "/nix/store/mbyy19mdwnfvfwmdi0gqgggx0njvpl1w-binutils-wrapper-2.46/bin/gmake"
      - "/nix/store/9k1lifnzmiybhh43argn30fb3sandm7a-hyprland-qtutils-0.1.5/bin/gmake"
      - "/nix/store/k0mncnynr1dljv26jabaagyd3fspkzc8-pciutils-3.15.0/bin/gmake"
      - "/nix/store/9c0l37g60k8w570jakcdz518m22dn9k8-pkgconf-wrapper-2.5.1/bin/gmake"
      - "/home/inurentto/.config/Code/User/globalStorage/github.copilot-chat/debugCommand/make"
      - "/home/inurentto/.config/Code/User/globalStorage/github.copilot-chat/copilotCli/make"
      - "/nix/store/flq8wn4dikbhn2nmqac31zbpv0lkii2w-glib-2.88.1-bin/bin/make"
      - "/nix/store/wp1cshqv98i8abs8rcx91s54igqgll0f-gawk-5.4.0/bin/make"
      - "/nix/store/gn94gpcp5q08x4v6g8mvw8v4r65rcjzk-gnugrep-3.12/bin/make"
      - "/nix/store/kgxafhycw2kybbqih759ykc2043qyi5j-gnused-4.9/bin/make"
      - "/nix/store/9ypz3flqsrl5xl495mm8h645gadjsxi1-coreutils-9.11/bin/make"
      - "/nix/store/91d9n98grpqj93576zl27bd5x0khcsvv-which-2.23/bin/make"
      - "/nix/store/74gap24knhy6dl59xnd7cksag4hns2vc-getconf-glibc-2.42-61/bin/make"
      - "/run/wrappers/bin/make"
      - "/home/inurentto/.local/share/flatpak/exports/bin/make"
      - "/var/lib/flatpak/exports/bin/make"
      - "/home/inurentto/.nix-profile/bin/make"
      - "/home/inurentto/.local/state/nix/profile/bin/make"
      - "/etc/profiles/per-user/inurentto/bin/make"
      - "/nix/var/nix/profiles/default/bin/make"
      - "/run/current-system/sw/bin/make"
      - "/nix/store/mbyy19mdwnfvfwmdi0gqgggx0njvpl1w-binutils-wrapper-2.46/bin/make"
      - "/nix/store/9k1lifnzmiybhh43argn30fb3sandm7a-hyprland-qtutils-0.1.5/bin/make"
      - "/nix/store/k0mncnynr1dljv26jabaagyd3fspkzc8-pciutils-3.15.0/bin/make"
      - "/nix/store/9c0l37g60k8w570jakcdz518m22dn9k8-pkgconf-wrapper-2.5.1/bin/make"
      - "/home/inurentto/.config/Code/User/globalStorage/github.copilot-chat/debugCommand/smake"
      - "/home/inurentto/.config/Code/User/globalStorage/github.copilot-chat/copilotCli/smake"
      - "/nix/store/flq8wn4dikbhn2nmqac31zbpv0lkii2w-glib-2.88.1-bin/bin/smake"
      - "/nix/store/wp1cshqv98i8abs8rcx91s54igqgll0f-gawk-5.4.0/bin/smake"
      - "/nix/store/gn94gpcp5q08x4v6g8mvw8v4r65rcjzk-gnugrep-3.12/bin/smake"
      - "/nix/store/kgxafhycw2kybbqih759ykc2043qyi5j-gnused-4.9/bin/smake"
      - "/nix/store/9ypz3flqsrl5xl495mm8h645gadjsxi1-coreutils-9.11/bin/smake"
      - "/nix/store/91d9n98grpqj93576zl27bd5x0khcsvv-which-2.23/bin/smake"
      - "/nix/store/74gap24knhy6dl59xnd7cksag4hns2vc-getconf-glibc-2.42-61/bin/smake"
      - "/run/wrappers/bin/smake"
      - "/home/inurentto/.local/share/flatpak/exports/bin/smake"
      - "/var/lib/flatpak/exports/bin/smake"
      - "/home/inurentto/.nix-profile/bin/smake"
      - "/home/inurentto/.local/state/nix/profile/bin/smake"
      - "/etc/profiles/per-user/inurentto/bin/smake"
      - "/nix/var/nix/profiles/default/bin/smake"
      - "/run/current-system/sw/bin/smake"
      - "/nix/store/mbyy19mdwnfvfwmdi0gqgggx0njvpl1w-binutils-wrapper-2.46/bin/smake"
      - "/nix/store/9k1lifnzmiybhh43argn30fb3sandm7a-hyprland-qtutils-0.1.5/bin/smake"
      - "/nix/store/k0mncnynr1dljv26jabaagyd3fspkzc8-pciutils-3.15.0/bin/smake"
      - "/nix/store/9c0l37g60k8w570jakcdz518m22dn9k8-pkgconf-wrapper-2.5.1/bin/smake"
    found: false
    search_context:
      ENV{PATH}:
        - "/home/inurentto/.config/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/home/inurentto/.config/Code/User/globalStorage/github.copilot-chat/copilotCli"
        - "/nix/store/flq8wn4dikbhn2nmqac31zbpv0lkii2w-glib-2.88.1-bin/bin"
        - "/nix/store/wp1cshqv98i8abs8rcx91s54igqgll0f-gawk-5.4.0/bin"
        - "/nix/store/gn94gpcp5q08x4v6g8mvw8v4r65rcjzk-gnugrep-3.12/bin"
        - "/nix/store/kgxafhycw2kybbqih759ykc2043qyi5j-gnused-4.9/bin"
        - "/nix/store/9ypz3flqsrl5xl495mm8h645gadjsxi1-coreutils-9.11/bin"
        - "/nix/store/91d9n98grpqj93576zl27bd5x0khcsvv-which-2.23/bin"
        - "/nix/store/74gap24knhy6dl59xnd7cksag4hns2vc-getconf-glibc-2.42-61/bin"
        - "/run/wrappers/bin"
        - "/home/inurentto/.local/share/flatpak/exports/bin"
        - "/var/lib/flatpak/exports/bin"
        - "/home/inurentto/.nix-profile/bin"
        - "/home/inurentto/.local/state/nix/profile/bin"
        - "/home/inurentto/.local/state/nix/profile/bin"
        - "/etc/profiles/per-user/inurentto/bin"
        - "/nix/var/nix/profiles/default/bin"
        - "/run/current-system/sw/bin"
        - "/nix/store/mbyy19mdwnfvfwmdi0gqgggx0njvpl1w-binutils-wrapper-2.46/bin"
        - "/nix/store/9k1lifnzmiybhh43argn30fb3sandm7a-hyprland-qtutils-0.1.5/bin"
        - "/nix/store/k0mncnynr1dljv26jabaagyd3fspkzc8-pciutils-3.15.0/bin"
        - "/nix/store/9c0l37g60k8w570jakcdz518m22dn9k8-pkgconf-wrapper-2.5.1/bin"
...
